name: Node CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Copy env file
        run: cp .env.example .env

      #Build and start Docker Compose (app + DB)
      - name: Build and start Docker compose
        run: docker compose up -d --build
        
      - name: wait for database to be ready
        run: |
          echo "wait for DB to init..."
          sleep 13

      #  Run Jest tests inside node-app container
      - name: Run tests inside Docker
        run: docker-compose run --rm node-app npm test

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest



